### ISSUE TITLE
votedFor Map grows without bound

### ISSUE THREAD

**Issue by colin-scott** [ktoso/akka-raft#57]
If you run akka-raft continuously, the votedFor hashmap continues to grow for every term increase. This can eventually lead to an OOM error.

Technically I think raft nodes should only need a single value for votedFor (the current term) rather than a Map containing every term.

**Comment by dmitraver** [comment]
I will make a PR soon.

**Comment by ktoso** [comment]
Thanks guys, agree that it's safe to only keep the `votedFor` :)
